# Generated by Django 4.2.23 on 2025-08-18 18:02

from django.db import migrations, models
import django.db.models.deletion
import stdimage.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('TMCore', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tm_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Codigo')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Descrição')),
                ('value', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Valor')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='tm_cst',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Codigo')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Descrição')),
                ('value', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Valor')),
            ],
            options={
                'verbose_name': 'CST',
                'verbose_name_plural': 'CSTs',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='tm_onu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Codigo')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Descrição')),
                ('value', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Valor')),
            ],
            options={
                'verbose_name': 'ONU',
                'verbose_name_plural': 'ONUs',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='tm_origin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Codigo')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Descrição')),
                ('value', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Valor')),
            ],
            options={
                'verbose_name': 'Origem',
                'verbose_name_plural': 'Origens',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='tm_risk_classification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Codigo')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Descrição')),
                ('value', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Valor')),
            ],
            options={
                'verbose_name': 'Classificacao de Risco',
                'verbose_name_plural': 'Classificacoes de Risco',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='tm_risk_number',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Codigo')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Descrição')),
                ('value', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Valor')),
            ],
            options={
                'verbose_name': 'Numero de Risco',
                'verbose_name_plural': 'Numeros de Risco',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=20, verbose_name='Codigo')),
                ('name', models.CharField(max_length=60, verbose_name='Nome')),
                ('ncm_excess', models.BooleanField(default=False, verbose_name='NCM Exceção')),
                ('net_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Peso liquido')),
                ('gross_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Peso bruto')),
                ('number_expiration_days', models.IntegerField(default=0, verbose_name='Qtde dias validade')),
                ('use_decimal_quantity', models.BooleanField(default=False, verbose_name='Usa decimal na quantidade')),
                ('use_stock_control', models.BooleanField(default=False, verbose_name='Usa controle de estoque')),
                ('use_serial_number', models.BooleanField(default=False, verbose_name='Usa número de série')),
                ('use_batch_expiration', models.BooleanField(default=False, verbose_name='Usa lote e validade')),
                ('use_controlled_product', models.BooleanField(default=False, verbose_name='Uso controlado')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Complemento')),
                ('tags', models.CharField(blank=True, max_length=100, null=True)),
                ('image', stdimage.models.StdImageField(blank=True, force_min_size=False, null=True, upload_to='items/', variations={'thumb': (124, 124)}, verbose_name='Imagem')),
                ('slug', models.SlugField(blank=True, editable=False, max_length=100, null=True)),
                ('box_height', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Altura da caixa')),
                ('box_width', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Largura da caixa')),
                ('box_length', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Comprimento da caixa')),
                ('box_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Peso da caixa')),
                ('box_quantity', models.IntegerField(default=0, verbose_name='Quantidade na caixa')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TMItem.tm_category')),
                ('cst', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TMItem.tm_cst')),
                ('onu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TMItem.tm_onu')),
                ('origin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TMItem.tm_origin')),
                ('risk_classification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TMItem.tm_risk_classification')),
                ('risk_number', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TMItem.tm_risk_number')),
                ('unit_measurement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TMCore.tm_unit_measurement')),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Itens',
                'ordering': ['name'],
            },
        ),
    ]
