# Generated by Django 4.2.23 on 2025-08-19 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TMItem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tm_category',
            name='complement',
            field=models.TextField(blank=True, null=True, verbose_name='Complemento'),
        ),
        migrations.AddField(
            model_name='tm_cst',
            name='complement',
            field=models.TextField(blank=True, null=True, verbose_name='Complemento'),
        ),
        migrations.AddField(
            model_name='tm_onu',
            name='complement',
            field=models.TextField(blank=True, null=True, verbose_name='Complemento'),
        ),
        migrations.AddField(
            model_name='tm_origin',
            name='complement',
            field=models.TextField(blank=True, null=True, verbose_name='Complemento'),
        ),
        migrations.AddField(
            model_name='tm_risk_classification',
            name='complement',
            field=models.TextField(blank=True, null=True, verbose_name='Complemento'),
        ),
        migrations.AddField(
            model_name='tm_risk_number',
            name='complement',
            field=models.TextField(blank=True, null=True, verbose_name='Complemento'),
        ),
        migrations.AlterField(
            model_name='tm_category',
            name='value',
            field=models.DecimalField(decimal_places=4, max_digits=10, null=True, verbose_name='Valor'),
        ),
        migrations.AlterField(
            model_name='tm_cst',
            name='value',
            field=models.DecimalField(decimal_places=4, max_digits=10, null=True, verbose_name='Valor'),
        ),
        migrations.AlterField(
            model_name='tm_onu',
            name='value',
            field=models.DecimalField(decimal_places=4, max_digits=10, null=True, verbose_name='Valor'),
        ),
        migrations.AlterField(
            model_name='tm_origin',
            name='value',
            field=models.DecimalField(decimal_places=4, max_digits=10, null=True, verbose_name='Valor'),
        ),
        migrations.AlterField(
            model_name='tm_risk_classification',
            name='value',
            field=models.DecimalField(decimal_places=4, max_digits=10, null=True, verbose_name='Valor'),
        ),
        migrations.AlterField(
            model_name='tm_risk_number',
            name='value',
            field=models.DecimalField(decimal_places=4, max_digits=10, null=True, verbose_name='Valor'),
        ),
    ]
