# Generated by Django 4.2.23 on 2025-08-19 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TMItem', '0002_tm_category_complement_tm_cst_complement_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tm_cst_icms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Codigo')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Descrição')),
                ('complement', models.TextField(blank=True, null=True, verbose_name='Complemento')),
                ('value', models.DecimalField(decimal_places=4, max_digits=10, null=True, verbose_name='Valor')),
            ],
            options={
                'verbose_name': 'CST ICMS',
                'verbose_name_plural': 'CSTs ICMS',
                'ordering': ['name'],
            },
        ),
    ]
