# Generated by Django 4.2.23 on 2025-08-19 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TMItem', '0003_tm_cst_icms'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tm_cst_icms',
        ),
    ]
