# Generated by Django 4.2.23 on 2025-08-20 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TMItem', '0004_delete_tm_cst_icms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data inclusão'),
        ),
        migrations.AlterField(
            model_name='item',
            name='current_status',
            field=models.BooleanField(default=True, verbose_name='Situação'),
        ),
        migrations.AlterField(
            model_name='item',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Data alteração'),
        ),
        migrations.AlterField(
            model_name='tm_category',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data inclusão'),
        ),
        migrations.AlterField(
            model_name='tm_category',
            name='current_status',
            field=models.BooleanField(default=True, verbose_name='Situação'),
        ),
        migrations.AlterField(
            model_name='tm_category',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Data alteração'),
        ),
        migrations.AlterField(
            model_name='tm_cst',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data inclusão'),
        ),
        migrations.AlterField(
            model_name='tm_cst',
            name='current_status',
            field=models.BooleanField(default=True, verbose_name='Situação'),
        ),
        migrations.AlterField(
            model_name='tm_cst',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Data alteração'),
        ),
        migrations.AlterField(
            model_name='tm_onu',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data inclusão'),
        ),
        migrations.AlterField(
            model_name='tm_onu',
            name='current_status',
            field=models.BooleanField(default=True, verbose_name='Situação'),
        ),
        migrations.AlterField(
            model_name='tm_onu',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Data alteração'),
        ),
        migrations.AlterField(
            model_name='tm_origin',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data inclusão'),
        ),
        migrations.AlterField(
            model_name='tm_origin',
            name='current_status',
            field=models.BooleanField(default=True, verbose_name='Situação'),
        ),
        migrations.AlterField(
            model_name='tm_origin',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Data alteração'),
        ),
        migrations.AlterField(
            model_name='tm_risk_classification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data inclusão'),
        ),
        migrations.AlterField(
            model_name='tm_risk_classification',
            name='current_status',
            field=models.BooleanField(default=True, verbose_name='Situação'),
        ),
        migrations.AlterField(
            model_name='tm_risk_classification',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Data alteração'),
        ),
        migrations.AlterField(
            model_name='tm_risk_number',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data inclusão'),
        ),
        migrations.AlterField(
            model_name='tm_risk_number',
            name='current_status',
            field=models.BooleanField(default=True, verbose_name='Situação'),
        ),
        migrations.AlterField(
            model_name='tm_risk_number',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Data alteração'),
        ),
    ]
