# Generated by Django 4.2.23 on 2025-08-25 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TMItem', '0005_alter_item_created_at_alter_item_current_status_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='tm_category',
            new_name='Category',
        ),
        migrations.RenameModel(
            old_name='tm_cst',
            new_name='CST',
        ),
        migrations.RenameModel(
            old_name='tm_onu',
            new_name='ONU',
        ),
        migrations.RenameModel(
            old_name='tm_origin',
            new_name='Origin',
        ),
        migrations.RenameModel(
            old_name='tm_risk_classification',
            new_name='RiskClassification',
        ),
        migrations.RenameModel(
            old_name='tm_risk_number',
            new_name='RiskNumber',
        ),
    ]
