# Generated by Django 4.2.23 on 2025-08-12 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tm_unit_measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('value', models.CharField(max_length=10)),
                ('current_status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Unidade Medida',
                'verbose_name_plural': 'Unidades de Medida',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(max_length=20, verbose_name='Codigo')),
                ('name', models.CharField(max_length=60)),
                ('ncm', models.CharField(blank=True, max_length=10, null=True)),
                ('ncm_excess', models.BooleanField(default=False)),
                ('cest', models.CharField(blank=True, max_length=10, null=True)),
                ('net_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('gross_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('number_expiration_days', models.IntegerField(default=0)),
                ('use_decimal_quantity', models.BooleanField(default=False)),
                ('use_stock_control', models.BooleanField(default=False)),
                ('use_serial_number', models.BooleanField(default=False)),
                ('use_batch_expiration', models.BooleanField(default=False)),
                ('use_controlled_product', models.BooleanField(default=False)),
                ('description', models.TextField()),
                ('tags', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='items/')),
                ('box_height', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('box_width', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('box_length', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('box_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('box_quantity', models.IntegerField(default=0)),
                ('current_status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('unit_measurement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TMSale.tm_unit_measurement')),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Items',
                'ordering': ['name'],
            },
        ),
    ]
