# Generated by Django 4.2.23 on 2025-08-26 16:17

import TMSale.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TMSale', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='alias',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='Apelido'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='cpf',
            field=models.CharField(max_length=14, null=True, unique=True, validators=[TMSale.models.validate_cpf], verbose_name='CPF'),
        ),
    ]
