# Generated by Django 4.2.23 on 2025-08-26 16:35

import TMSale.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TMSale', '0004_alter_contact_alias_alter_contact_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='cpf',
            field=models.CharField(blank=True, max_length=14, null=True, unique=True, validators=[TMSale.models.validate_cpf], verbose_name='CPF'),
        ),
    ]
