# Generated by Django 4.2.23 on 2025-08-20 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TMCore', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tm_currency',
            name='complement',
            field=models.TextField(blank=True, null=True, verbose_name='Complemento'),
        ),
        migrations.AddField(
            model_name='tm_unit_measurement',
            name='complement',
            field=models.TextField(blank=True, null=True, verbose_name='Complemento'),
        ),
        migrations.AlterField(
            model_name='tm_currency',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='tm_currency',
            name='value',
            field=models.DecimalField(decimal_places=4, max_digits=10, null=True, verbose_name='Valor'),
        ),
        migrations.AlterField(
            model_name='tm_unit_measurement',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='tm_unit_measurement',
            name='value',
            field=models.DecimalField(decimal_places=4, max_digits=10, null=True, verbose_name='Valor'),
        ),
    ]
