# Generated by Django 4.2.23 on 2025-08-20 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TMCore', '0002_tm_currency_complement_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tm_currency',
            name='CodeWebServiceBCB_Buy',
        ),
        migrations.RemoveField(
            model_name='tm_currency',
            name='CodeWebServiceBCB_Sale',
        ),
        migrations.RemoveField(
            model_name='tm_currency',
            name='SymbolBeforeValue',
        ),
        migrations.AddField(
            model_name='tm_currency',
            name='codeWeb_service_BCB_buy',
            field=models.IntegerField(blank=True, null=True, verbose_name='Código BCB - compra'),
        ),
        migrations.AddField(
            model_name='tm_currency',
            name='codeWeb_service_BCB_sale',
            field=models.IntegerField(blank=True, null=True, verbose_name='Código BCB - venda'),
        ),
        migrations.AddField(
            model_name='tm_currency',
            name='symbol_before_value',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Simbolo'),
        ),
        migrations.AlterField(
            model_name='company',
            name='alias',
            field=models.CharField(max_length=50, unique=True, verbose_name='Fantasia'),
        ),
        migrations.AlterField(
            model_name='company',
            name='cnpj',
            field=models.CharField(max_length=14, unique=True, verbose_name='CNPJ'),
        ),
        migrations.AlterField(
            model_name='company',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data inclusão'),
        ),
        migrations.AlterField(
            model_name='company',
            name='current_status',
            field=models.BooleanField(default=True, verbose_name='Situação'),
        ),
        migrations.AlterField(
            model_name='company',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='e-mail'),
        ),
        migrations.AlterField(
            model_name='company',
            name='homedirectory',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Diretório base'),
        ),
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='company_logos/', verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Razão social'),
        ),
        migrations.AlterField(
            model_name='company',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='company',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Data alteração'),
        ),
        migrations.AlterField(
            model_name='tm_currency',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data inclusão'),
        ),
        migrations.AlterField(
            model_name='tm_currency',
            name='current_status',
            field=models.BooleanField(default=True, verbose_name='Situação'),
        ),
        migrations.AlterField(
            model_name='tm_currency',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Data alteração'),
        ),
        migrations.AlterField(
            model_name='tm_unit_measurement',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data inclusão'),
        ),
        migrations.AlterField(
            model_name='tm_unit_measurement',
            name='current_status',
            field=models.BooleanField(default=True, verbose_name='Situação'),
        ),
        migrations.AlterField(
            model_name='tm_unit_measurement',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Data alteração'),
        ),
    ]
