# Generated by Django 4.2.23 on 2025-08-21 12:19

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('TMCore', '0003_remove_tm_currency_codewebservicebcb_buy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=stdimage.models.StdImageField(blank=True, force_min_size=False, null=True, upload_to='company_logos/', variations={'thumbnail': {'height': 200, 'width': 200}}, verbose_name='Logo'),
        ),
    ]
