# Generated by Django 4.2.23 on 2025-08-25 20:43

import TMCore.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TMItem', '0006_rename_tm_category_category_rename_tm_cst_cst_and_more'),
        ('TMCore', '0004_alter_company_logo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='tm_currency',
            new_name='Currency',
        ),
        migrations.RenameModel(
            old_name='tm_unit_measurement',
            new_name='UnitMeasurement',
        ),
        migrations.AlterField(
            model_name='company',
            name='cnpj',
            field=models.CharField(max_length=14, unique=True, validators=[TMCore.models.validate_cnpj], verbose_name='CNPJ'),
        ),
    ]
